name: simple-workflow 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #{owner}/{repository}@{ref}
        with:
         ref: main  #If you want to control which branch of your repository is checked out, you can specify it explicitly:

      - name: Setup GO Version
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      - run: go run helloworld.go
